package org.jetbrains.research.tasktracker.tracking.activity

import org.joda.time.DateTime

/**
 * Structure that encompasses all the data that needs to be logged for any activity.
 */
data class ActivityEvent(
    val time: DateTime,
    val type: Type,
    /**
     * Information about the activity, depending on its type.
     */
    val info: String,
    /**
     * Selected text in current project.
     */
    val selectedText: String? = null,
    /**
     * Used to connect Shortcut and Action
     */
    val id: String? = null
)

enum class Type {
    /**
     * Actions generated by the IntelliJ Platform.
     */
    Action,

    /**
     * Execution processes that were launched from an IDE.
     */
    Execution,

    /**
     * Applying any shortcut in IDE.
     */
    Shortcut,

    /**
     * Pressing any key on the keyboard in the current project.
     */
    KeyPressed,

    /**
     * Releasing any key on the keyboard in the current project.
     */
    KeyReleased
}
